[sfu]
#ices = ["stun:stun.stunprotocol.org:3478"]
single = true
pprof = ":6060"

[log]
level = "info"

[etcds]
servers = ["localhost:2379"]

[signal]
host = "0.0.0.0"
port = "8443"
certpem = "conf/cert.pem"
keypem = "conf/key.pem"



