[mode]
standalone = true
signal = "protoo"

[log]
level = "info"

[etcds]
servers = ["localhost:2379"]

[centrifugo]
url = "wss://localhost:8000/connection/websocket"
key = "secret"
certpem = "conf/cert.pem"
keypem = "conf/key.pem"
expire = 0

[protoo]
host = "0.0.0.0"
port = "8443"
certpem = "conf/cert.pem"
keypem = "conf/key.pem"


[sfu]
#ices = ["stun:stun.stunprotocol.org:3478"]

