name: flutter_pion
version: 0.0.1
author: pion
description: webrtc plugin for pion sfu. 
homepage: https://github.com/pion/sfu
environment:
  sdk: '>1.8.0 <3.0.0'

dependencies:
  uuid: ^2.0.1
  events2: ^0.1.3
  sdp_transform: ^0.1.0
  flutter_webrtc:
    git: https://github.com/cloudwebrtc/flutter-webrtc.git
  protoo_client:
    git: https://github.com/cloudwebrtc/dart-protoo-client.git
